import type { Lang } from '@/utils/types';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Aside from '@/components/Aside';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import Main from '@/components/Main';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export interface ILayoutProps {
  children: React.ReactNode;
  params: Promise<{
    lng: Lang;
  }>;
}

export default async function RootLayout({ children, params }: Readonly<ILayoutProps>) {
  const { lng } = await params;
  return (
    <html lang={lng}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        <div className="wrapper grid grid-cols-[250px_auto]">
          <Aside />
          <Main>{children}</Main>
        </div>
        <Footer lang={lng} />
      </body>
    </html>
  );
}
